/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import LessonsBehavior from "./LessonsBehavior";
import "./lessons.css";
export const metadata: Metadata = {
 title: "עמרי ברגר — שיעורי תופים בתל אביב",
 description: "שיעורי תופים אישיים עם עמרי ברגר בסטודיו פרטי במרכז תל אביב. מתחילים משיר, ומתקדמים בקצב שלך.",
};
export default function LessonsPage() { return <div className="omri-lessons">
<a className="skip" href="#main">דילוג לתוכן</a><header className="topbar wrap"><a className="logo" href="#">עמרי ברגר<span>מתופף · מורה לתופים</span></a><span className="status">מקבל תלמידים חדשים</span></header><main id="main">
<section className="opening wrap" aria-labelledby="hero-title"><div className="hero-copy"><h1 id="hero-title">תמיד רצית<br />לנגן על תופים?</h1><p className="sub">בוא.י נתחיל משיר.</p><p className="intro">לא חצי שנה של תרגילים לפני שמנגנים. יושבים על הסט, לומדים גרוב אחד, שמים אוזניות — ומנגנים שיר.</p></div><figure className="hero-photo"><img src="/marketing/lessons/stage.jpg" alt="עמרי על הבמה, מאחורי מערכת התופים עם מקלות מורמים" width="1280" height="1920" fetchPriority="high" /><figcaption><span>על הבמה</span><bdi>Arctic Kartiv</bdi></figcaption></figure><div className="hero-action"><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%2C%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%90%D7%A0%D7%99%20%D7%A8%D7%95%D7%A6%D7%94%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%A9%D7%99%D7%A2%D7%95%D7%A8%D7%99%20%D7%AA%D7%95%D7%A4%D7%99%D7%9D%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a><div className="cta-meta">שיחה קצרה בוואטסאפ, בלי טפסים.<br />סטודיו פרטי במרכז תל אביב</div></div></section>
<section className="first wrap section" aria-labelledby="first-title"><img className="drawing snare" src="/marketing/lessons/snare.png" alt="" width="1536" height="1024" loading="lazy" /><div className="section-grid"><h2 id="first-title" className="reveal">יושבים.<br />מנגנים.<br /><em>בונים משם.</em></h2><div className="body-copy"><p>לא צריך להתכונן לפני שמתחילים. בשיעור הראשון נכיר קצת, נתיישב מאחורי התופים ונמצא את נקודת ההתחלה שלך.</p><p>נלמד מקצב פשוט, נשים שיר באוזניות ונתחיל לחבר את הדברים. בלי למהר, ובלי הבטחות קסם — עם מקום לנסות, לטעות ולגלות.</p><p>ומשם ממשיכים גם בבית — לכל תלמיד.ה יש אזור אישי עם מה שעבדנו עליו בשיעור.</p></div></div></section>
<section className="philosophy section"><div className="wrap"><h2 className="statement reveal">לא חייבים לרצות להיות מוזיקאים מקצועיים כדי לקחת את התופים <em>ברצינות!</em></h2><p>אפשר לנגן בשביל הכיף, ועדיין לרצות להשתפר באמת.</p></div></section>
<section className="personal wrap section"><div className="section-grid"><div><h2 className="reveal">מה יקדם<br />את הנגינה שלך?</h2><p>אין מסלול אחד שמתאים לכולם. נבחר יחד על מה לעבוד, לפי המקום שלך היום והמוזיקה שבא לך לנגן.</p></div><ul className="topics"><li><span>גרוב</span><small>לגרום למקצב להרגיש טוב.</small></li><li><span>טכניקה ותיאום</span><small>לנגן בנוחות, בחופש ובשליטה.</small></li><li><span>זמן והקשבה</span><small>למצוא את המקום שלך בתוך המוזיקה.</small></li><li><span>שירים</span><small>לחבר את מה שלומדים לנגינה אמיתית.</small></li></ul></div></section>
<aside className="conversion"><div className="wrap"><h2>בוא.י לשנות את החיים שלך לתמיד.</h2><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%2C%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%90%D7%A0%D7%99%20%D7%A8%D7%95%D7%A6%D7%94%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%A9%D7%99%D7%A2%D7%95%D7%A8%D7%99%20%D7%AA%D7%95%D7%A4%D7%99%D7%9D%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div></aside>
<section className="studio section"><div className="wrap"><div className="section-grid"><div><h2 className="reveal">להיכנס.<br />לשים אוזניות.<br />להתחיל לנגן.</h2></div><div className="body-copy"><p>סטודיו פרטי ונעים במרכז תל אביב, עם טיפול אקוסטי, מערכת תופים מקצועית וכל מה שצריך כדי לעשות מוזיקה.</p><p>התופים מחוברים ומוכנים להקלטה. כשזה עוזר לתהליך, אפשר להקליט, להקשיב לעצמנו ולשמוע דברים שקשה לשים לב אליהם תוך כדי נגינה.</p></div></div><div className="studio-photos"><img src="/marketing/lessons/studio.jpg" alt="מערכת התופים והציוד בסטודיו" width="1200" height="900" loading="lazy" /><img src="/marketing/lessons/studio-detail.jpg" alt="מבט מקרוב על ציוד התופים בסטודיו" width="900" height="900" loading="lazy" /><span className="place-note">נפגשים<br />בתל אביב.</span></div></div></section>
<section className="practice section"><div className="wrap section-grid"><div><h2 className="reveal">השיעור לא נגמר<br />כשקמים מהתופים.</h2><p>לא צריך לצאת מהסטודיו ולנסות לזכור הכול. באזור האישי שלך, מה שעשינו בשיעור נשאר מסודר גם להמשך השבוע.</p><p className="practice-end">וזה רק מתחיל.</p></div><ol className="practice-list"><li>סיכום של מה שעבדנו עליו</li><li>שיעורי בית וקבצים לתרגול</li><li>לינקים לשירים</li><li>לינק לקביעת השיעור הבא</li></ol></div></section>
<aside className="conversion"><div className="wrap"><h2>שווה לפחות לנסות פעם אחת, לא?</h2><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%2C%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%90%D7%A0%D7%99%20%D7%A8%D7%95%D7%A6%D7%94%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%A9%D7%99%D7%A2%D7%95%D7%A8%D7%99%20%D7%AA%D7%95%D7%A4%D7%99%D7%9D%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div></aside>
<section className="music section wrap"><div className="section-grid"><div><h2 className="reveal">בסוף,<br />מנגנים מוזיקה.</h2><p>התרגילים הם חלק מהדרך. השירים, ההקשבה והמפגש עם עוד נגנים הם מה שנותן לה משמעות.</p><p>נלמד לא רק מה לנגן, אלא איך התופים מתחברים לכל מה שקורה מסביב.</p></div><img className="drawing headphones" src="/marketing/lessons/headphones.png" alt="" width="1536" height="1024" loading="lazy" /></div><figure className="live"><img src="/marketing/lessons/live.jpg" alt="עמרי מנגן עם ההרכב מול קהל בהופעה" width="1920" height="1505" loading="lazy" /><figcaption>מהסטודיו אל המוזיקה שבחוץ.</figcaption></figure></section>
<figure className="quote"><blockquote dir="ltr">YOU HAVE TO PLAY<br /><em>FOR</em> THE MUSIC.</blockquote><figcaption>צריך לנגן בשביל המוזיקה.<span dir="ltr">— Steve Gadd</span></figcaption></figure>
<section className="about section wrap"><div className="section-grid"><div><h2 className="reveal">נעים להכיר,<br />אני עמרי.</h2><p className="about-note"><bdi>11</bdi> שנות נגינה.<br />והרבה מוזיקה בדרך.</p></div><div className="body-copy"><p>ב־<bdi>11</bdi> השנים האחרונות יצא לי לנגן ולהופיע בהרבה מסגרות שונות — מבמות גדולות ועד הופעות קטנות ואינטימיות, ברוק, ג׳אז, אירועים ועוד. היום אני מנגן ב־<bdi>Arctic Kartiv</bdi>, הרכב המחווה הישראלי ל־<bdi>Arctic Monkeys</bdi>, ובין היתר הופענו מול כ־<bdi>800</bdi> איש בגגרין בתל אביב.</p><p>לאורך הדרך הופעתי גם בפסטיבל סמילנסקי בבאר שבע, ניגנתי בהרכבים שונים ובמשך תקופה ארוכה ניגנתי ג׳אז בבתי קפה. מכל מורה ומכל מפגש לקחתי דברים שממשיכים להשפיע על הדרך שבה אני מנגן ומלמד.</p><p>אני מלמד כי אני באמת אוהב את זה. הדרך כמוזיקאי לימדה אותי על נגינה, אימון, התקדמות והתמודדות עם תקיעות — ואני אוהב להעביר את זה הלאה. מוזיקה יכולה להכניס לחיים עולם שלם שאפשר להמשיך ללמוד, לחקור וליהנות ממנו במשך שנים.</p></div></div><div className="teachers">למדתי אצל <bdi>Tom Bollig</bdi> · איתמר ויינשטיין · שי זלמן · שחר אדרי · עופרי נחמיה</div></section>

<section className="final section wrap" id="start"><div><h2 className="reveal">נו, אז מתי<br /><em>מתחילים?</em></h2><p>שיחה קצרה, היכרות — ומשם לתופים.</p><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%2C%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%90%D7%A0%D7%99%20%D7%A8%D7%95%D7%A6%D7%94%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%A9%D7%99%D7%A2%D7%95%D7%A8%D7%99%20%D7%AA%D7%95%D7%A4%D7%99%D7%9D%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div><img className="offer-badge" src="/marketing/lessons/lesson-199-badge.png" alt="שיעור ראשון — 199 שקלים, 40 דקות" width="1536" height="1024" loading="lazy" /></section>
</main><footer className="wrap"><span>עמרי ברגר · שיעורי תופים בתל אביב</span><a href="/students/login">כניסה לתלמידים</a></footer><div className="sticky" id="stickyCta" hidden><div className="wrap"><span>בוא.י נתחיל משיר.<small>שיעורי תופים בתל אביב</small></span><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%2C%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%90%D7%A0%D7%99%20%D7%A8%D7%95%D7%A6%D7%94%20%D7%9C%D7%A9%D7%9E%D7%95%D7%A2%20%D7%A2%D7%9C%20%D7%A9%D7%99%D7%A2%D7%95%D7%A8%D7%99%20%D7%AA%D7%95%D7%A4%D7%99%D7%9D%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div></div><LessonsBehavior /></div>; }
