/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import LessonsBehavior from "./LessonsBehavior";
import "./lessons.css";
export const metadata: Metadata = {
 title: "עמרי ברגר — שיעורי תופים בתל אביב",
 description: "שיעורי תופים אישיים עם עמרי ברגר בסטודיו פרטי במרכז תל אביב. מתחילים משיר, ומתקדמים בקצב שלך.",
};
export default function LessonsPage() { return <div className="omri-lessons">
<a className="skip" href="#main">דילוג לתוכן</a><header className="topbar wrap"><a className="logo" href="#">עמרי ברגר<span>מתופף · מורה לתופים</span></a></header><main id="main">
<section className="opening wrap" aria-labelledby="hero-title"><div className="hero-copy"><h1 id="hero-title">תמיד רצית<br />לנגן על תופים?</h1><p className="sub">בואו נתחיל מהשיר האהוב עליכם.ן!</p><p className="intro">אפשר לנגן בשביל הכיף.<br />אפשר לחלום על הבמות הגדולות.<br />בשני המקרים — מתחילים משיעור ניסיון אצלי :)</p></div><figure className="hero-photo"><img src="/marketing/lessons/stage.jpg" alt="עמרי על הבמה, מאחורי מערכת התופים עם מקלות מורמים" width="1280" height="1920" fetchPriority="high" /><figcaption><span>על הבמה</span><bdi>Arctic Kartiv</bdi></figcaption></figure><div className="hero-action"><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%21%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%91%D7%90%20%D7%9C%D7%99%20%D7%9C%D7%A0%D7%A1%D7%95%D7%AA%20%D7%9C%D7%A0%D7%92%D7%9F%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a><div className="cta-meta">שיחה קצרה בוואטסאפ, בלי טפסים.<br />סטודיו פרטי במרכז תל אביב</div></div></section>
<section className="first wrap section"><img className="drawing snare" src="/marketing/lessons/snare.png" alt="" width="1536" height="1024" loading="lazy" /><div className="section-grid"><h2 className="reveal">יושבים.<br />מנגנים.<br />ומתמכרים.</h2><div className="body-copy"><p>לא צריך לדעת כלום על מוזיקה לפני שמגיעים לשיעור הראשון!</p><p>תבואו, נכיר קצת, תתיישבו על התופים — ותתחילו לנגן!</p><p>ולפני שתשימו לב, כבר נקליט שיר ראשון להשמיע למשפחה ולחברים :)</p><p>ואם זה ההישג הראשון שלכם.ן על התופים — הוא כבר נכנס לאזור האישי שלכם.ן 🏆</p><p><strong>כן, יש לכם אזור אישי. עוד נגיע לזה.</strong></p></div></div></section>
<section className="philosophy section"><div className="wrap"><h2 className="statement reveal">לא כולם רוצים להיות מתופפים מקצועיים.<br />אבל כולן רוצות להרגיש שהן משתפרות.</h2><p>אפשר לבוא בשביל הכיף, בשביל לנגן את השירים שאוהבים או עם חלום להגיע יום אחד לבמות הגדולות. נבנה את השיעורים לפי החלום שלכם.ן!</p></div></section>
<section className="personal wrap section"><div className="section-grid"><div><h2 className="reveal">אז מה בא לך לדעת לנגן?</h2><p>אין תכנית אחת שכולם צריכים לעבור. נבין מה בא לך להשיג — ונלמד את הדברים שיעזרו לך להגיע לשם.</p></div><ul className="topics"><li><span>לנגן את השירים שאת אוהבת</span><small>לפרק שירים, ללמוד אותם ולנגן מההתחלה ועד הסוף.</small></li><li><span>להרגיש טוב על התופים</span><small>לעבוד על גרוב, זמן והקשבה עד שהנגינה שלך באמת יושבת.</small></li><li><span>לנגן דברים שלא הצלחת לנגן קודם</span><small>טכניקה, קואורדינציה, מהירות — וכל מה שעומד בינך לבין הדבר שבא לך לנגן.</small></li><li><span>לנגן עם אנשים</span><small>להבין מה התפקיד של המתופפת ואיך גורמים ללהקה להישמע טוב יותר.</small></li></ul></div><p><strong>ובינתיים, הכול נשמר.</strong></p><p>מה כבר הצלחתם, על מה עובדים עכשיו ומה הדבר הבא — מחכה לכם באזור האישי.</p></section>
<aside className="conversion"><div className="wrap"><h2 className="reveal">אם הגעת עד לכאן, כנראה שיש לך חוש קצב.<br />בוא.י לשיעור ניסיון!</h2><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%21%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%91%D7%90%20%D7%9C%D7%99%20%D7%9C%D7%A0%D7%A1%D7%95%D7%AA%20%D7%9C%D7%A0%D7%92%D7%9F%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div></aside>
<section className="studio section"><div className="wrap"><div className="section-grid"><div><h2 className="reveal">פה עושים רעש.<br />והשכנים אפילו בסדר עם זה.</h2></div><div className="body-copy"><p>הסטודיו נמצא במרכז תל אביב (!) ברחוב דרויאנוב 5.</p><p>מגיעים, שמים את הדברים בצד, מתיישבים על התופים ובוחרים מה בא לנגן היום. יש מערכת תופים מקצועית, אוזניות וכל מה שצריך — לא צריך להביא כלום.</p><p>והכי כיף — הכול מחובר ומוכן להקלטה. מסיימים לעבוד על שיר, מקליטים אתכם, ובדרך הביתה כבר שולחים לאמא סרטון שלכם מתופפים :)</p><p>והתווים, שיעורי הבית וכל מה שצריך כדי להמשיך בבית? כבר מחכים לכם באזור האישי.</p></div></div><div className="studio-photos"><img src="/marketing/lessons/studio.jpg" alt="מערכת התופים והציוד בסטודיו" width="1200" height="900" loading="lazy" /><img src="/marketing/lessons/studio-detail.jpg" alt="מבט מקרוב על ציוד התופים בסטודיו" width="900" height="900" loading="lazy" /></div></div></section>
<section className="practice section"><div className="wrap section-grid"><div><h2 className="reveal">השיעור נגמר. אבל אתם לא נשארים לבד עד לשבוע הבא.</h2><p>לכל מי שלומד אצלי יש אזור אישי שממשיך איתנו משיעור לשיעור.</p><p>יומיים אחרי השיעור מתיישבים להתאמן ולא זוכרים מה אמרתי? פותחים את הטלפון. מחכים שם שיעורי הבית, התווים שכתבתי לכם, השירים שאנחנו עובדים עליהם ובאיזה קצב להתחיל.</p></div><div className="body-copy"><p>משהו לא ברור בתרגול? דרך האזור האישי אפשר לענות על כמה שאלות קצרות ולהגיד לי בדיוק איפה נתקעתם ומה לא מסתדר — כדי שנדע על מה צריך לעבוד.</p><p><strong>והחלק שאני הכי אוהב — ההישגים שלכם.ן.</strong></p><p>הצלחתם לנגן שיר שלם בפעם הראשונה? עברתם קצב שעבדנו עליו כבר חודש? ניגנתן עם עוד מוזיקאים בפעם הראשונה?</p><p>זה נכנס לאזור ההישגים שלכם.ן.</p><p>ככה לאורך הזמן לא רק מרגישים שמתקדמים — אפשר לפתוח את האזור האישי ולראות את כל הדברים שפעם לא ידעתם לעשות והיום כבר כן.</p><p>וכשמגיעים לשיעור הבא, לא מתחילים מחדש. אני כבר יודע מה תרגלתם, איפה היה קשה ומה הצלחנו לעשות בפעם הקודמת — וממשיכים משם.</p><p>וכן, גם את השיעור הבא קובעים משם :)</p></div></div></section>
<aside className="conversion"><div className="wrap"><h2 className="reveal">שווה לנסות לפחות פעם אחת בחיים, לא?</h2><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%21%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%91%D7%90%20%D7%9C%D7%99%20%D7%9C%D7%A0%D7%A1%D7%95%D7%AA%20%D7%9C%D7%A0%D7%92%D7%9F%20%F0%9F%A5%81">בא לי לנגן<span aria-hidden="true">↗</span></a></div></aside>
<section className="music section wrap"><div className="section-grid"><div><h2 className="reveal">בסוף, מנגנים מוזיקה.</h2><p>המטרה היא לא להיות אלופות בלנגן תרגילים בחדר לבד.</p><p>המטרה היא לשים שיר באוזניות ולהרגיש שאתן יושבות עליו בול. לעלות לנגן עם חברות ולא ללכת לאיבוד. לשמוע שיר שאתן אוהבות ופתאום להבין מה המתופפת עושה שם.</p><p>ואולי יום אחד גם לעלות על במה ולספור לכולן:</p><p><strong><bdi>ONE, TWO, THREE, FOUR!</bdi></strong></p></div><img className="drawing headphones" src="/marketing/lessons/headphones.png" alt="" width="1536" height="1024" loading="lazy" /></div><figure className="live"><img src="/marketing/lessons/live.jpg" alt="עמרי מנגן עם ההרכב מול קהל בהופעה" width="1920" height="1505" loading="lazy" /><figcaption>מהסטודיו אל המוזיקה שבחוץ.</figcaption></figure></section>
<figure className="quote"><blockquote dir="ltr">YOU HAVE TO PLAY<br /><em>FOR THE MUSIC.</em></blockquote><figcaption>צריך לנגן בשביל המוזיקה.<span dir="ltr">— Steve Gadd</span></figcaption></figure>
<section className="about section wrap"><div className="section-grid"><div><h2 className="reveal">אהלן, אני עמרי :)</h2><p className="about-note">אני מתופף כבר 11 שנה, ועדיין מתרגש מתופים בצורה קצת מוגזמת.</p></div><div className="body-copy"><p>יצא לי לנגן על במות גדולות, בהופעות קטנות, בפסטיבלים, בבתי קפה ובלא מעט חדרי חזרות. היום אני מנגן ומופיע במסגרות שונות — בין היתר עם <strong><bdi>Arctic Kartiv</bdi></strong>, הרכב המחווה הישראלי ל־<bdi>Arctic Monkeys</bdi>, שאיתו הופענו מול בערך 800 איש בגגרין בתל אביב, וגם עם הרכבים לאירועים ובהופעות נוספות.</p><p>אבל האמת היא שרוב הדרך שלי בתופים נראתה הרבה פחות זוהרת — שעות של אימונים, שירים שלא הצלחתי לנגן, דברים שנתקעתי עליהם שבועות, מורים ששינו לי את הדרך שבה אני חושב על הכלי, והרגע הכיפי הזה שמשהו פתאום מצליח.</p><p>אני רוצה שתצאו מהשיעורים שלי עם יותר מוזיקה בחיים. שתשמעו שירים אחרת, שתתלהבו כשמשהו סוף סוף יושב, שתנגנו עם אנשים, ואולי בעוד כמה שנים תסתכלו אחורה ולא תבינו איך פעם לא ידעתם לנגן על תופים.</p><p>במהלך השנים זכיתי ללמוד אצל <strong><bdi>Tom Bollig</bdi>, איתמר ויינשטיין, שי זלמן, שחר אדרי ועופרי נחמיה.</strong> מכל אחד מהם לקחתי משהו אחר — על נגינה, מוזיקה, אימון ולמידה — ואת הדברים האלה אני ממשיך לקחת איתי גם לשיעורים שאני מעביר.</p></div></div></section>
<section className="final section wrap" id="start"><div><h2 className="reveal">נו, אז מתי מתחילים?</h2><p>לוחצים על הכפתור, שולחים לי הודעה בוואטסאפ, מוצאים זמן שמתאים — ונפגשים בסטודיו :)</p><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%21%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%91%D7%90%20%D7%9C%D7%99%20%D7%9C%D7%A0%D7%A1%D7%95%D7%AA%20%D7%9C%D7%A0%D7%92%D7%9F%20%F0%9F%A5%81">יאללה קובעים.ות 🥁<span aria-hidden="true">↗</span></a></div><img className="offer-badge" src="/marketing/lessons/lesson-199-badge.png" alt="שיעור ראשון — 199 שקלים, 40 דקות" width="1536" height="1024" loading="lazy" /></section>
</main><footer className="wrap"><span>עמרי ברגר · שיעורי תופים בתל אביב</span><a href="/students/login">כניסה לתלמידים</a></footer><div className="sticky" id="stickyCta" hidden><div className="wrap"><span>בואו נתחיל מהשיר האהוב עליכם.ן!<small>שיעורי תופים בתל אביב</small></span><a className="btn" href="https://wa.me/972545379987?text=%D7%94%D7%99%D7%99%20%D7%A2%D7%9E%D7%A8%D7%99%21%20%D7%94%D7%92%D7%A2%D7%AA%D7%99%20%D7%93%D7%A8%D7%9A%20%D7%94%D7%90%D7%AA%D7%A8%20%D7%95%D7%91%D7%90%20%D7%9C%D7%99%20%D7%9C%D7%A0%D7%A1%D7%95%D7%AA%20%D7%9C%D7%A0%D7%92%D7%9F%20%F0%9F%A5%81">יאללה קובעים.ות 🥁<span aria-hidden="true">↗</span></a></div></div><LessonsBehavior /></div>; }
