import { getGoogleCalendarCredentials, saveGoogleCalendarCredentials } from "@/lib/cloud/supabaseRest";
import { LessonBooking, LessonSchedule } from "@/lib/types";

const TOKEN_URL="https://oauth2.googleapis.com/token";
const API="https://www.googleapis.com/calendar/v3";
function client(){const id=process.env.GOOGLE_CALENDAR_CLIENT_ID,secret=process.env.GOOGLE_CALENDAR_CLIENT_SECRET;if(!id||!secret)throw new Error("Missing GOOGLE_CALENDAR_CLIENT_ID/SECRET");return{id,secret}}
export function googleAuthUrl(origin:string,state:string){const {id}=client();const q=new URLSearchParams({client_id:id,redirect_uri:`${origin}/api/google-calendar/callback`,response_type:"code",scope:"https://www.googleapis.com/auth/calendar",access_type:"offline",prompt:"consent",state});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`}
export async function exchangeGoogleCode(code:string,origin:string){const {id,secret}=client();const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:id,client_secret:secret,redirect_uri:`${origin}/api/google-calendar/callback`,grant_type:"authorization_code"})});if(!r.ok)throw new Error(`Google token exchange failed: ${await r.text()}`);const j=await r.json();await saveGoogleCalendarCredentials({accessToken:j.access_token,refreshToken:j.refresh_token,expiresAt:Date.now()+Number(j.expires_in||3600)*1000});}
async function accessToken(){let c=await getGoogleCalendarCredentials();if(!c?.refreshToken&&!c?.accessToken)throw new Error("Google Calendar is not connected");if(c.accessToken&&c.expiresAt&&c.expiresAt>Date.now()+60000)return c.accessToken;const {id,secret}=client();if(!c.refreshToken)return c.accessToken!;const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:id,client_secret:secret,refresh_token:c.refreshToken,grant_type:"refresh_token"})});if(!r.ok)throw new Error(`Google token refresh failed: ${await r.text()}`);const j=await r.json();c={...c,accessToken:j.access_token,expiresAt:Date.now()+Number(j.expires_in||3600)*1000};await saveGoogleCalendarCredentials(c);return c.accessToken!}
async function gfetch(path:string,init:RequestInit={}){const token=await accessToken();const r=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(`Google Calendar API failed ${r.status}: ${await r.text()}`);return r}
export async function calendarConnectionInfo(){try{await accessToken();const [cals,colors]=await Promise.all([gfetch('/users/me/calendarList').then(r=>r.json()),gfetch('/colors').then(r=>r.json())]);return{connected:true,calendars:(cals.items||[]).filter((c:any)=>["owner","writer"].includes(c.accessRole)).map((c:any)=>({id:c.id,name:c.summary,primary:Boolean(c.primary)})),colors:Object.entries(colors.event||{}).map(([id,v]:any)=>({id,background:v.background,foreground:v.foreground}))}}catch{return{connected:false,calendars:[],colors:[]}}}
function eventTitle(schedule:LessonSchedule,b:LessonBooking){return(schedule.googleCalendar.eventTitleTemplate||"שיעור תופים — {student}").split("{student}").join(b.studentName)}
export async function createLessonEvent(schedule:LessonSchedule,b:LessonBooking){const calendarId=encodeURIComponent(schedule.googleCalendar.calendarId||"primary");const body:any={summary:eventTitle(schedule,b),start:{dateTime:`${b.date}T${b.startTime}:00`,timeZone:"Asia/Jerusalem"},end:{dateTime:`${b.date}T${b.endTime}:00`,timeZone:"Asia/Jerusalem"},description:`NEXT · תלמיד: ${b.studentName}`};if(schedule.googleCalendar.eventColorId)body.colorId=schedule.googleCalendar.eventColorId;const j=await gfetch(`/calendars/${calendarId}/events`,{method:"POST",body:JSON.stringify(body)}).then(r=>r.json());return j.id as string}
export async function deleteLessonEvent(schedule:LessonSchedule,eventId:string){const token=await accessToken();const calendarId=encodeURIComponent(schedule.googleCalendar.calendarId||"primary");const r=await fetch(`${API}/calendars/${calendarId}/events/${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!r.ok&&r.status!==404)throw new Error(`Google event delete failed: ${await r.text()}`)}
