"use client";
import { useEffect,useState } from "react";
import { Student } from "@/lib/types";
type Day={date:string;weekday:number;dayName:string;displayDate:string;times:string[]};
type Existing={id:string;date:string;startTime:string;endTime:string;canModify:boolean}|null;
function displayDate(value:string){const [y,m,d]=value.split("-");return `${d}.${m}.${y}`}
export function StudentBookingFlow({student}:{student:Student}){
  const[open,setOpen]=useState(false),[days,setDays]=useState<Day[]>([]),[day,setDay]=useState<Day|null>(null),[other,setOther]=useState(false),[text,setText]=useState(""),[loading,setLoading]=useState(true),[done,setDone]=useState<"booking"|"request"|"cancel"|null>(null),[existing,setExisting]=useState<Existing>(null),[confirmCancel,setConfirmCancel]=useState(false);const female=student.gender==="female";
  async function load(){setLoading(true);const r=await fetch(`/api/student/${student.shareToken}/schedule`,{cache:"no-store"});setLoading(false);if(r.ok){const j=await r.json();setDays(j.days||[]);setExisting(j.existing||null)}}
  useEffect(()=>{load()},[student.shareToken]);
  async function book(time:string){if(!day)return;setLoading(true);const r=await fetch(`/api/student/${student.shareToken}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"book",date:day.date,startTime:time})});setLoading(false);if(r.status===409){await load();setDay(null);return}if(r.ok){setDone("booking");setExisting({id:"",date:day.date,startTime:time,endTime:"",canModify:true})}}
  async function request(){if(!text.trim())return;setLoading(true);const r=await fetch(`/api/student/${student.shareToken}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"request",preferredDay:day?.date,message:text.trim()})});setLoading(false);if(r.ok)setDone("request")}
  async function change(action:"cancel"|"reschedule"){
    setLoading(true);const r=await fetch(`/api/student/${student.shareToken}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});setLoading(false);
    if(r.status===403){await load();return}
    if(r.ok){setExisting(null);setConfirmCancel(false);if(action==="reschedule"){setDone(null);setOpen(true);setDay(null);setOther(false);await load()}else setDone("cancel")}
  }
  if(loading&&!open&&!existing)return <div className="bg-surface rounded-card p-5 shadow-card mt-6"><p className="text-sm text-muted">בודק את השיעור הבא…</p></div>;
  if(existing&&!done)return <div className="bg-[#183f32] text-white rounded-card p-5 shadow-card mt-6"><p className="text-xs font-bold text-white/60">השיעור הבא שלך</p><p className="text-2xl font-extrabold mt-2">{displayDate(existing.date)} · {existing.startTime}{existing.endTime?`–${existing.endTime}`:""}</p><p className="text-sm text-white/70 mt-2">מחכה לך 🥁</p>{existing.canModify&&<div className="grid grid-cols-2 gap-2 mt-4"><button disabled={loading} onClick={()=>change("reschedule")} className="bg-white text-[#183f32] rounded-button-sm py-3 font-extrabold">הזזת שיעור</button><button disabled={loading} onClick={()=>setConfirmCancel(true)} className="bg-white/10 text-white rounded-button-sm py-3 font-extrabold">ביטול שיעור</button></div>}{confirmCancel&&<div className="bg-white text-text rounded-button-sm p-4 mt-3"><p className="font-bold">לבטל את השיעור?</p><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>setConfirmCancel(false)} className="bg-surface-soft rounded-button-sm py-2 font-bold">לא</button><button onClick={()=>change("cancel")} className="bg-[#6f1831] text-white rounded-button-sm py-2 font-extrabold">כן, לבטל</button></div></div>}{!existing.canModify&&<p className="text-xs text-white/60 mt-4">פחות מ־24 שעות לפני השיעור אי אפשר לבטל או להזיז דרך NEXT.</p>}</div>;
  if(done==="cancel")return <div className="bg-surface rounded-card p-6 shadow-card mt-6"><p className="text-2xl font-extrabold">השיעור בוטל</p><button onClick={()=>{setDone(null);setOpen(true);load()}} className="w-full bg-[#6f1831] text-white rounded-button-sm py-3 font-extrabold mt-4">קביעת שיעור חדש</button></div>;
  if(!open)return <button onClick={()=>setOpen(true)} className="w-full bg-[#6f1831] text-white rounded-button-sm py-4 px-5 font-extrabold text-lg shadow-card mt-6">🥁 קביעת שיעור</button>;
  if(done==="request")return <div className="bg-surface rounded-card p-6 shadow-card mt-6"><p className="text-2xl font-extrabold">סבבה 😄</p><p className="text-muted mt-2">עמרי יבדוק אם אפשר להזיז ויעדכן אותך!</p></div>;
  if(done==="booking")return <div className="bg-[#183f32] text-white rounded-card p-6 shadow-card mt-6"><p className="text-2xl font-extrabold">יש! השיעור נקבע 🥁</p><p className="text-white/70 mt-2">ברפרוש הבא יופיע כאן השיעור הבא שלך.</p></div>;
  if(other)return <div className="bg-surface rounded-card p-5 shadow-card mt-6"><button onClick={()=>setOther(false)} className="text-sm font-bold text-muted">→ חזרה</button><h2 className="text-2xl font-extrabold mt-4">{female?"מתי את יכולה?":"מתי אתה יכול?"}</h2><p className="text-muted mt-1">אפשר לכתוב יום ושעה שנוחים לך.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="למשל: רביעי אחרי 17:30" className="w-full min-h-28 bg-surface-soft rounded-button-sm p-4 mt-4 outline-none"/><button disabled={!text.trim()||loading} onClick={request} className="w-full bg-text text-white rounded-button-sm py-3 font-extrabold mt-3 disabled:opacity-40">{loading?"שולח…":"אישור"}</button></div>;
  if(day)return <div className="bg-surface rounded-card p-5 shadow-card mt-6"><button onClick={()=>setDay(null)} className="text-sm font-bold text-muted">→ חזרה</button><h2 className="text-2xl font-extrabold mt-4">יופיי, {female?"את יכולה ב:":"אתה יכול ב:"}</h2><p className="text-sm text-muted mt-1">יום {day.dayName} · {day.displayDate}</p><div className="grid grid-cols-3 gap-2 mt-4">{day.times.map(t=><button disabled={loading} key={t} onClick={()=>book(t)} className="bg-text text-white rounded-button-sm py-4 font-extrabold text-lg">{t}</button>)}</div><button onClick={()=>setOther(true)} className="w-full bg-surface-soft rounded-button-sm py-3 px-3 font-bold mt-4">{female?"לא יכולה בשעות האלו, אני יכולה ב…":"לא יכול בשעות האלו, אני יכול ב…"}</button></div>;
  return <div className="bg-surface rounded-card p-5 shadow-card mt-6"><button onClick={()=>setOpen(false)} className="text-sm font-bold text-muted">סגירה ×</button><h2 className="text-2xl font-extrabold mt-4">איזה כיףף 😄</h2><p className="text-lg font-bold mt-1">{female?"מתי את פנויה השבוע?":"מתי אתה פנוי השבוע?"}</p>{loading&&!days.length?<p className="text-muted mt-5">בודק שעות…</p>:<div className="grid grid-cols-3 gap-2 mt-5">{days.map(d=><button key={d.date} onClick={()=>setDay(d)} className="bg-[#183f32] text-white rounded-button-sm py-4 px-2 font-extrabold"><span className="block">יום {d.dayName}</span><span className="block text-xs opacity-70 mt-1">{d.displayDate}</span></button>)}</div>}<button onClick={()=>setOther(true)} className="w-full bg-surface-soft rounded-button-sm py-3 px-3 font-bold mt-4">{female?"אני לא פנויה בזמנים האלו — לשאול את עמרי על יום אחר":"אני לא פנוי בזמנים האלו — לשאול את עמרי על יום אחר"}</button></div>
}
